In [1]:
import pandas as pd
import numpy as np

In [2]:
target = pd.read_csv("YM2014.csv")
league = pd.read_csv("MLB2014.csv")
injury_date = (7.10,)
recovered_date = (8.27,)
strong_start = (0,)
strong_end = (0,)
min_to_be_Strong = 162
min_to_be_Average = 162

In [3]:
target = target[['Date', 'Tm', 'Opp', 'W/L']]
league = league[['Tm', 'W']]
league =league.rename(columns={'Tm' : 'Opp'})

In [4]:
league.drop(league.tail(1).index,inplace=True) # drop last 1 rows

In [5]:
target[target['Opp'] == 'MIN']

In [6]:
new_win = []
new_total = []
pro = []
for i in league.index:
    new_win.append(league['W'][i] - len(target[ (target['Opp' ]== league['Opp'][i]) & (target['W/L'].str.contains("L")) ]))
    #new_total.append( 162-len(target[ (target['Opp']== league['Opp'][i])] )
    pro.append(  round( 162 *     (league['W'][i] - len(target[ (target['Opp' ]== league['Opp'][i]) & (target['W/L'].str.contains("L")) ]) )      /      (162-len(target[ (target['Opp' ]== league['Opp'][i])]) ) ) )
league['Isolated_W'] = new_win 
#league['Isolated_All'] = new_total
league['probability'] = pro

73
84

In [ ]:
league = league.sort_values(by = ['probability'])
league = league.reset_index(drop=True)
league

In [ ]:
print(league['probability'][9])
print(league['probability'][20])

In [10]:
#helper function to modify the date data for later analysis
def modi_date(date):
    date_dict = {
        'Mar': '3',
        'Apr': '4',
        'May': '5',
        'Jun': '6',
        'Jul': '7',
        'Aug': '8',
        'Sep': '9',
        'Oct': '10'
    }
    date_split = date.split(" ")[1:]
    d = date_dict[date_split[0]]
    return float('{}.{:0>2}'.format(date_dict[date_split[0]], date_split[1]))

In [11]:
df = pd.merge(target, league, on = 'Opp')
df['Date'] = df['Date'].apply(modi_date)
df = df.sort_values(by = ['Date'])
df = df.reset_index(drop=True)

In [12]:
def get_winning_games_number(team_name: str):
    return league[league['Opp'] == team_name]['probability'].values[0]

In [13]:
#helper function to get the classify an opponent's status: weak, average, or strong
def get_oppo_status(team_name: str):
    w_n = get_winning_games_number(team_name)
    if w_n >= min_to_be_Strong:
        return "Strong"
    elif min_to_be_Average <= w_n < min_to_be_Strong:
        return 'Average'
    else:
        return "Weak"

In [14]:
def get_avaliablity(date):
    for inj, rec in zip(injury_date, recovered_date):
        if inj <= date <= rec:
            return False
    return True

In [15]:
def is_Strong(date):
    for start, end in zip(strong_start, strong_end):
        if start <= date < end:
            return True
    return False

In [16]:
frame = pd.DataFrame({
                      'Date': df['Date'], 
                      "Aval": df['Date'].apply(get_avaliablity), 
                      "Strong": df['Date'].apply(is_Strong),
                      "Opp-Status": df['Opp'].apply(get_oppo_status),
                      'Opp': df['Opp'],
                      'W/L': df['W/L'], 
                      'Opp-W': df['Isolated_W'],
                      'Opp-W-percentage': df['probability']
                      })
frame.to_excel('YM2014.xlsx')

In [ ]:
frame

In [17]:
#helper funtion to calculate the number of the games in which the target team and its
#opponent are classifies as a particular status.
def count_category(data, strong=False, opp_status=None):
    strong_series = data['Strong'] if strong else data['Strong'] == False
    c1 = len(data[strong_series & (frame['Opp-Status'].str.match(opp_status))])
    a1 = len(data)
    #print('numerator :    ', c1)
    #print('denumerator : ', a1)
    #print('output: ', c1/a1)
    return c1/a1

In [18]:
def count_win(data, aval=False, strong=False, opp_status=None):
    aval_series = data['Aval'] if aval else data['Aval'] == False
    strong_series = data['Strong'] if strong else data['Strong'] == False
    win = len(data[(data['W/L'].str.contains("W")) & aval_series & strong_series & (frame['Opp-Status'].str.match(opp_status))])
    number_of_all_games =  len(data[aval_series & strong_series & (frame['Opp-Status'].str.match(opp_status))])
    #print('numerator :    ', win)
    #print('denumerator : ', number_of_all_games)
    if number_of_all_games == 0:
        #print('output: ', 0)
        return 0
    else: 
        #print('output: ', win/number_of_all_games)
        return win/number_of_all_games

In [19]:
def get_WAR(data = frame):
    
    #print('P_Aval_Weak_weakOpp :')
    aval_weak_weak = count_win(data, aval = True, strong = False, opp_status="Weak") 
    #print('P_Unaval_Weak_weakOpp :')
    unaval_weal_weak = count_win(data, aval = False, strong = False, opp_status="Weak")
    #print('P X = Weak_weakOpp :')
    weak_weak = count_category(data, strong = False, opp_status="Weak")
    
    #print('P_Aval_Weak_averageOpp :')
    aval_weak_average = count_win(data, aval = True, strong = False, opp_status="Average")
    #print('P_Unaval_Weak_averageOpp :')
    unaval_weak_average = count_win(data, aval = False, strong = False, opp_status="Average")
    #print('P X = Weak_averageOpp :')
    weak_average = count_category(data, strong = False, opp_status="Average")
    
    #print('P_Aval_Weak_strongOpp :')
    aval_weak_strong = count_win(data, aval = True, strong = False, opp_status="Strong")
    #print('P_Unaval_Weak_strongOpp :')
    unaval_weak_strong = count_win(data, aval = False, strong = False, opp_status="Strong")
    #print('P X = Weak_strongOpp :')
    weak_strong = count_category(data, strong = False, opp_status="Strong")
    
    #print('P_Aval_Strong_weakOpp :')
    aval_strong_weak = count_win(data, aval = True, strong = True, opp_status="Weak") 
    #print('P_Unaval_Strong_weakOpp :')
    unaval_strong_weak = count_win(data, aval = False, strong = True, opp_status="Weak")
    #print('P X = Strong_weakOpp :')
    strong_weak = count_category(data, strong = True, opp_status="Weak")
    
    #print('P_Aval_Strong_averageOpp :')
    aval_strong_average = count_win(data, aval = True, strong = True, opp_status="Average")
    #print('P_Unaval_Strong_averageOpp :')
    unaval_strong_average = count_win(data, aval = False, strong = True, opp_status="Average")
    #print('P X = Strong_averageOpp :')
    strong_average = count_category(data, strong = True, opp_status="Average")
    
    #print('P_Aval_Strong_strongOpp :')
    aval_strong_strong = count_win(data, aval = True, strong = True, opp_status="Strong")
    #print('P_Unaval_Strong_strongOpp :')
    unaval_strong_strong = count_win(data, aval = False, strong = True, opp_status="Strong")
    #print('P X = Strong_strongOpp :')
    strong_strong = count_category(data, strong = True, opp_status="Strong")
    
    war = ((aval_weak_weak - unaval_weal_weak)* weak_weak
           + (aval_weak_average - unaval_weak_average)* weak_average
           + (aval_weak_strong - unaval_weak_strong)* weak_strong 
           + (aval_strong_weak - unaval_strong_weak)* strong_weak
           + (aval_strong_average - unaval_strong_average)* strong_average 
           + (aval_strong_strong - unaval_strong_strong)* strong_strong) * 119
    return war

In [20]:
def WAR_change_oppSAW():
    output = []
    new_df = frame
    for i in range(80,95):
        for j in range(70, i):
            
            #helper function to change the data
            def new_opp_status(team_name: str):
                w_n = get_winning_games_number(team_name)
                if w_n >= i:
                    return "Strong"
                elif j <= w_n < i:
                    return 'Average'
                else:
                    return "Weak"
                
            new_df['Opp-Status'] = new_df['Opp'].apply(new_opp_status)
            twar = round(get_WAR(new_df), 4)
            temp = [i, j, twar]
            output.append(temp)
    return output

In [21]:
x = WAR_change_oppSAW()

In [22]:
factor1 = []
factor2 = []
result = []
for row in x:
    factor1.append(row[0])
    factor2.append(row[1])
    result.append(row[2])
df2 = pd.DataFrame({
    'min_to_be_Strong': factor1,
    'min_to_be_Average': factor2,
    'war': result
    })
df2 = df2.pivot(index='min_to_be_Average', columns='min_to_be_Strong', values='war')
df2.to_excel('YM2014_Isolate_target_win.xlsx')

In [23]:
df2.to_excel('YM2014_Isolate_target_win.xlsx')

In [24]:
df2

min_to_be_Strong,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94
min_to_be_Average,,,,,,,,,,,,,,,
70,3.5732,2.0694,2.0694,1.9303,1.9303,1.7634,1.7634,1.8087,1.8087,1.8087,1.8087,1.7438,1.7438,1.7438,1.7438
71,4.2383,2.9674,2.9674,2.9627,2.9627,2.9654,2.9654,3.1288,3.1288,3.1288,3.1288,2.9083,2.9083,2.9083,2.9083
72,4.2383,2.9674,2.9674,2.9627,2.9627,2.9654,2.9654,3.1288,3.1288,3.1288,3.1288,2.9083,2.9083,2.9083,2.9083
73,4.2383,2.9674,2.9674,2.9627,2.9627,2.9654,2.9654,3.1288,3.1288,3.1288,3.1288,2.9083,2.9083,2.9083,2.9083
74,5.8842,4.5023,4.5023,4.3965,4.3965,4.3004,4.3004,4.4259,4.4259,4.4259,4.4259,4.2021,4.2021,4.2021,4.2021
75,5.5875,5.6655,5.6655,5.5196,5.5196,5.4139,5.4139,5.5969,5.5969,5.5969,5.5969,4.9023,4.9023,4.9023,4.9023
76,8.8460,7.4162,7.4162,8.3663,8.3663,9.5836,9.5836,10.5608,10.5608,10.5608,10.5608,6.8828,6.8828,6.8828,6.8828
77,8.8460,7.4162,7.4162,8.3663,8.3663,9.5836,9.5836,10.5608,10.5608,10.5608,10.5608,6.8828,6.8828,6.8828,6.8828
78,6.5013,6.1734,6.1734,7.0924,7.0924,8.2914,8.2914,9.2551,9.2551,9.2551,9.2551,6.3045,6.3045,6.3045,6.3045
79,6.5013,6.1734,6.1734,7.0924,7.0924,8.2914,8.2914,9.2551,9.2551,9.2551,9.2551,6.3045,6.3045,6.3045,6.3045
80,NaN,6.1734,6.1734,7.0924,7.0924,8.2914,8.2914,9.2551,9.2551,9.2551,9.2551,6.3045,6.3045,6.3045,6.3045
81,NaN,NaN,5.3450,7.5057,7.5057,10.1301,10.1301,11.9465,11.9465,11.9465,11.9465,3.9982,3.9982,3.9982,3.9982
82,NaN,NaN,NaN,7.5057,7.5057,10.1301,10.1301,11.9465,11.9465,11.9465,11.9465,3.9982,3.9982,3.9982,3.9982
83,NaN,NaN,NaN,NaN,5.0289,7.6533,7.6533,9.4697,9.4697,9.4697,9.4697,4.3548,4.3548,4.3548,4.3548
84,NaN,NaN,NaN,NaN,NaN,7.6533,7.6533,9.4697,9.4697,9.4697,9.4697,4.3548,4.3548,4.3548,4.3548
85,NaN,NaN,NaN,NaN,NaN,NaN,4.6674,6.4837,6.4837,6.4837,6.4837,4.6131,4.6131,4.6131,4.6131
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.4837,6.4837,6.4837,6.4837,4.6131,4.6131,4.6131,4.6131
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6317,4.6317,4.6317,4.7199,4.7199,4.7199,4.7199
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6317,4.6317,4.7199,4.7199,4.7199,4.7199
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6317,4.7199,4.7199,4.7199,4.7199
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.7199,4.7199,4.7199,4.7199
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5827,4.5827,4.5827
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5827,4.5827
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5827